### ISSUE TITLE
emails for employees

### ISSUE THREAD

**Issue by GitaVYBE** [VYBEproductions/VYBE-pm#10]

**Comment by LoganVYBE** [comment]
Need email for Adriana and any new teammates/get them into Zenhub

**Comment by ghost** [comment]
Yes, I still need to learn about Zenhub.

**Comment by GitaVYBE** [comment]
I can set up a session for us all to do a Q&A on github/zenhub

**Comment by LoganVYBE** [comment]
Yeah, that'd be great! Once we're all familiar this workflow will be super natural!
