### ISSUE TITLE
medical information for crew

### ISSUE THREAD

**Issue by GitaVYBE** [VYBEproductions/VYBE-pm#22]

**Comment by GitaVYBE** [comment]
each employee needs to fill this out: https://docs.google.com/document/d/1hS37CCO0hLzpf9Mdblwp9hUnQIZkF9SU/edit?usp=sharing&ouid=100352187085065957238&rtpof=true&sd=true

**Comment by ghost** [comment]
[VYBE  Employee Emergency Contact Form - Plunkett.pdf](https://github.com/VYBEproductions/VYBE-pm/files/8758506/Vybe.Employee.Emergency.Contact.Form.-.Plunkett.pdf)

**Comment by GitaVYBE** [comment]
Thanks and yes! these are now combined!

**Comment by LoganVYBE** [comment]
Dang, I filled this out and just need to export it, I can do that as soon as I get home
